yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "p4-css@*":
    dependencies:
      "tslib": "*"
  "react-embed@*":
    dependencies:
      "tslib": "*"
  "react-simple-player@*":
    dependencies:
      "tslib": "*"

